#!/bin/sh
# Default paths to external tools
# DO NOT EDIT THIS FILE, create own `config.sh` and put modifications there
#
# `export FOO=bar` is a bashism and not portable
#
# A shell script should use the following two lines to include
# `config_default.sh` and optionally `config.sh`:
#
#     . PATH/TO/config_default.sh
#     [ ! -e PATH/TO/config.sh ] || . PATH/TO/config.sh
#


# any gcc for risc-v, libs are not used
RV_PREFIX=riscv64-unknown-elf-
export RV_PREFIX

# gcc with libs compiled for RV32I
RV32I_PREFIX=riscv32i-unknown-elf-
export RV32I_PREFIX

IVERILOG=iverilog
export IVERILOG

VVP=vvp
export VVP

VERILATOR=verilator
export VERILATOR

YOSYS=yosys
export YOSYS

ARACHNE=arachne-pnr 
export ARACHNE

NEXTPNR_ICE40=nextpnr-ice40
export NEXTPNR_ICE40

ICEPACK=icepack
export ICEPACK

ICETIME=icetime
export ICETIME

ICEPROG=iceprog
export ICEPROG

VIVADO=vivado
export VIVADO

# path (with trailing slash) to Quartus bin directory (or nothing if in $PATH)
#QUARTUS_BIN=
#export QUARTUS_BIN

# Microsemi Libero SoC executable
#LIBEROSOC="$HOME/.local/microsemi/Libero_SoC_v12.1/Libero/bin/libero"
#export LIBEROSOC
