# Default paths to external tools
# DO NOT EDIT THIS FILE, create a new file config.mk instead and 
# put your modifications there

# any gcc for risc-v, libs are not used
RV_PREFIX = riscv64-unknown-elf-

# gcc with libs compiled for RV32I
RV32I_PREFIX = riscv32i-unknown-elf-

IVERILOG = iverilog
VVP = vvp
YOSYS = yosys
ARACHNE = arachne-pnr 
NEXTPNR_ICE40 = nextpnr-ice40
ICEPACK = icepack
ICETIME = icetime
ICEPROG = iceprog

-include $(dir $(abspath $(lastword $(MAKEFILE_LIST))))config.mk