# Default paths to external tools
# DO NOT EDIT THIS FILE, create a new file config.mk instead and 
# put your modifications there

RV32_PREFIX = riscv32-unknown-elf-
IVERILOG = iverilog
VVP = vvp
YOSYS = yosys
ARACHNE = arachne-pnr 
NEXTPNR_ICE40 = nextpnr-ice40
ICEPACK = icepack
ICETIME = icetime
ICEPROG = iceprog

-include config.mk