RISCV_PREFIX   ?= riscv32-unknown-elf-
RISCV_GCC      ?= $(RISCV_PREFIX)gcc
RISCV_GCC_OPTS ?= -static -mcmodel=medany -fvisibility=hidden -nostdlib

COMPILE_TARGET=\
    $$(RISCV_GCC) $(1) $$(RISCV_GCC_OPTS) \
        -I$(ROOTDIR)/riscv-test-suite/env/ \
        -I$(TARGETDIR)/$(RISCV_TARGET)/ \
        -T$(TARGETDIR)/$(RISCV_TARGET)/link.ld \
        $$< -o $$@;

RUN_TARGET=\
    $(TARGETDIR)/../../../scripts/sim/run_arch_test.sh \
    $< $*.signature.output

